name: "Bug report"
description: Create a report to help us improve
title: "[Bug]: "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        This form is only for submitting bug reports. If you have a usage question
        or are unsure if this is really a bug, make sure to:

        - Read the [docs](https://documentation.mapcraft.app)
        - Ask on [Discord Chat](https://discord.gg/PMEFsW3ac9)
  - type: textarea
    id: reproduction-link
    attributes:
      label: Link or code for minimal reproduction
      description: |
        The reproduction should be contain only the bare minimum amount of code needed to show the bug.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        What do we need to do after opening your repro in order to make the bug happen? Clear and concise reproduction instructions are important for us to be able to triage your issue in a timely manner. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code.
      placeholder: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is expected?
    validations:
      required: true
  - type: textarea
    id: actually-happening
    attributes:
      label: What is happening?
    validations:
      required: true
  - type: dropdown
    id: system-info
    attributes:
      label: OS
      description: What operating system do you use ?
      options:
        - Windows
        - Linux
        - MacOS
        - Other
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments ?
      description: log, error, ...