name: "Feature request"
description: Suggest an idea for this project
title: "[Feature]: "
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        This form is only for submitting feature requests. If you have a usage question
        or are unsure if this is really a bug, make sure to:

        - Read the [docs](https://documentation.mapcraft.app)
        - Ask on [Discord Chat](https://discord.gg/PMEFsW3ac9)
  - type: textarea
    id: problem-description
    attributes:
      label: What problem does this feature solve ?
      description: |
        Explain your use case, context, and rationale behind this feature request. More importantly, what is the **end user experience** you are trying to build that led to the need for this feature ?
      placeholder: Problem description
    validations:
      required: true
  - type: textarea
    id: proposed-API
    attributes:
      label: What does the proposed API look like?
      description: |
        Describe how you propose to solve the problem and provide code samples of how the API would work once implemented.
      placeholder: proposed
    validations:
      required: true